"""pub0 - PUBLIC-EXPORT SANITISATION as ONE declared, exact, reversible proof-chain transition.

WHY. The public repository must not spell the owner's Home Assistant device slug (its area prefix names where the dongle is)
or the Octopus meter serial / MPANs (docs/public-release/PUBLIC_RELEASE_BUILD_SPEC.md C.1 items 1-3 and 9). About forty
suites pin those very files byte for byte (sha256, exact-match reverters, chain checkpoints). A find-and-replace would turn them
red, and re-hashing them is forbidden (_scope_chain.py: "No older suite is re-hashed, ever"). So the sanitisation is a declared
transition, the project's own technique: every edit is recorded, applied exactly, verified, and undone exactly for the proofs.

WHAT pub0 CHANGES (the complete list; the spec names nothing else as a token substitution):
  slug          the private device slug (PRIVATE_SLUG) -> PUBLIC_SLUG, the slug a fresh Home Assistant install generates for
                the firmware's `name: ecco-clock-dongle` (spec C.2)
  meter_serial  the Octopus meter serial inside `octopus_energy_electricity_<serial>_<mpan>_...` ids -> `your_meter_serial`
  import_mpan   the import MPAN in those ids -> `your_import_mpan`
  export_mpan   the export MPAN (the ids that continue `_export_`) -> `your_export_mpan`
  export_flag   EXPORTED below: False -> True (the declared marker that a tree IS the pub0 export)
  wording       an unsupported provenance attribution in the register map (WORDING below: the private wording -> a neutral
                public wording; register facts unchanged; PUBLIC_RELEASE_BUILD_SPEC D)
  attribution   a personal first name in six register-map descriptions (ATTRIBUTION below: "SmartDeye/<first name>-listed" ->
                "SmartDeye-listed"; the descriptions are otherwise unchanged)
and it KEEPS, as declared exemptions (sites of kind keep / keep_prefix, counted like every other site):
  keep          (no sites since the public-export assembly) the private slug inside a generated HISTORICAL hunk module. The two
                such modules (_fbb3_ha_scope.py, _fbc3_scope.py) now carry a marker and bind the slug from PRIVATE_SLUG at import
                (their bound hunks are pinned by test_pub0_transition.py [7]), so they spell no private literal at all
  keep_prefix   the one PRIVATE_AREA_PREFIX literal below, which private_view() needs to rebuild the private text
The public export therefore carries exactly TWO private literals, both reverter data in THIS module and nowhere else: the
PRIVATE_AREA_PREFIX literal and the ATTRIBUTION_PRIVATE literal (machine-checked by test_pub0_privacy.py [1] and
tools/tests/test_public_privacy.py [1]). The register map is chain-pinned at the root checkpoint, so only an EXACT reverse can
reproduce that pin; removing the first name from the reverter too would mean re-hashing the root pin, which is forbidden.

HOW. registry/tests/fixtures/pub0_manifest.json (GENERATED by generate() / tools/public/pub0.py; reviewed, never hand-edited)
lists every target file with its source and result sha256 and, per changed line, the line number, the sha256 (16 hex) of the
PUBLIC line and the sites [column in the public line, kind]. The manifest spells no private value: the private side of a site
is the rule of its kind, the Octopus values are matched by shape and never stored.
  forward(rel, private_text) -> public text   (export direction) ACCEPTS ONLY the declared source: every site's private token at
                its exact place, every private-prefix occurrence and every Octopus id in the file covered by a site (no more, no
                fewer), one value per Octopus kind, no Octopus value left anywhere, the masked source sha256 and the result
                sha256 exactly as recorded. Anything else raises Pub0Error.
  reverse(rel, public_text) -> private representation (proof direction) - edit-local like every chain reverter: each declared
                line must be exactly the recorded public line (its hash) with the public token at the recorded column, and only
                those sites are undone. It is NOT a generic replace: the slug already spelled un-prefixed in the private tree
                (`esphome.ecco_clock_dongle_fallback_profile_execute`, `sensor.ecco_clock_dongle_wifi_signal`) is left alone.
                The Octopus values are irreversible by design (not in the public tree): reverse() leaves the placeholders.
  private_view(rel, text) is what an older suite calls before a historical pin: the identity in the private tree (and for
                every file pub0 does not touch), reverse() in the public export.
The scope chain carries pub0 as an Entry (registry/tests/_scope_chain.py, PUB0) whose reverter for the only chain-pinned artifact
pub0 edits (registry/inverter_capabilities.yaml) is reverse(); it is part of CHAIN only when EXPORTED.

No I/O except reading the manifest and repo files.
"""

from __future__ import annotations

import hashlib
import json
import re
from functools import lru_cache
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
MANIFEST_REL = "registry/tests/fixtures/pub0_manifest.json"
SELF_REL = "registry/tests/_pub0_scope.py"
SCHEMA = "ecco-pub0-manifest/1"

# The export marker. pub0 flips it (site kind export_flag): False in the private development tree, True in the public export.
EXPORTED = True

PUBLIC_SLUG = "ecco_clock_dongle"
PRIVATE_AREA_PREFIX = "garden_"          # pub0 keep_prefix site: the ONE private literal the public export carries (see the docstring)
PRIVATE_SLUG = PRIVATE_AREA_PREFIX + PUBLIC_SLUG

OCTOPUS_PLACEHOLDER = {"meter_serial": "your_meter_serial", "import_mpan": "your_import_mpan", "export_mpan": "your_export_mpan"}
OCTOPUS_SHAPE = {"meter_serial": re.compile(r"[0-9]{2}[a-z][0-9]{7}"), "import_mpan": re.compile(r"[0-9]{13}"),
                 "export_mpan": re.compile(r"[0-9]{13}")}
OCTOPUS_LEN = {"meter_serial": 10, "import_mpan": 13, "export_mpan": 13}
# An Octopus Energy integration id with a real serial and MPAN (lower-case, as Home Assistant spells it).
OCTOPUS_ID = re.compile(r"octopus_energy_electricity_([0-9]{2}[a-z][0-9]{7})_([0-9]{13})_(export_)?")
EXPORT_FLAG_LINE = re.compile(r"^EXPORTED = (False|True)$", re.M)

# The one declared provenance rewording (kind wording): the register map's description of register 214 attributed its bit meaning
# to "Deye protocol" without citing any document (PUBLIC_RELEASE_BUILD_SPEC D: origin UNKNOWN). The public wording keeps the
# register facts and drops the unsupported attribution. Not private data: the private wording is reverter data, as for every kind.
WORDING_PRIVATE = "Deye protocol: bit0 0=Enable, 1=Disable."
WORDING_PUBLIC = "bit0 0=Enable, 1=Disable (as decoded by ECCO; no vendor document is cited)."
# The declared personal-name removal (kind attribution): six register-map descriptions of the SmartDeye parity candidates name the
# person who listed them. The public wording drops the name. This literal is reverter data (see the docstring): the ONE place the
# public export spells that first name; LOW privacy risk (a first name only), location and count machine-checked.
ATTRIBUTION_PRIVATE = "SmartDeye/Barry-listed"
ATTRIBUTION_PUBLIC = "SmartDeye-listed"
ATTRIBUTION_FILES = frozenset({"registry/inverter_capabilities.yaml"})


def attribution_name() -> str:
    """The personal first name inside ATTRIBUTION_PRIVATE (derived, never spelled a second time)."""
    head, tail = "SmartDeye/", "-listed"
    if not (ATTRIBUTION_PRIVATE.startswith(head) and ATTRIBUTION_PRIVATE.endswith(tail)):
        raise ValueError("ATTRIBUTION_PRIVATE is not of the declared form SmartDeye/<name>-listed")
    return ATTRIBUTION_PRIVATE[len(head):-len(tail)]


KINDS = ("slug", "meter_serial", "import_mpan", "export_mpan", "export_flag", "keep", "keep_prefix", "wording", "attribution")
REVERSIBLE = frozenset({"slug", "export_flag", "keep", "keep_prefix", "wording", "attribution"})
PRIVATE_TOKEN = {"slug": PRIVATE_SLUG, "export_flag": "False", "keep": PRIVATE_SLUG, "keep_prefix": PRIVATE_AREA_PREFIX,
                 "wording": WORDING_PRIVATE, "attribution": ATTRIBUTION_PRIVATE}
PUBLIC_TOKEN = {"slug": PUBLIC_SLUG, "export_flag": "True", "keep": PRIVATE_SLUG, "keep_prefix": PRIVATE_AREA_PREFIX,
                "wording": WORDING_PUBLIC, "attribution": ATTRIBUTION_PUBLIC, **OCTOPUS_PLACEHOLDER}

# ---------------------------------------------------------------------------------------------------------------------------
# The declared target set (spec section B: every file the public export carries that spells a pub0 token), and its policy.
# ---------------------------------------------------------------------------------------------------------------------------
# Generated historical hunk modules whose private slug is proof data: none since the public-export assembly (they bind the slug from
# PRIVATE_SLUG at import; see the docstring). Kept as an empty, checked policy so a regression to literal hunks is caught.
KEEP_FILES = frozenset()
OCTOPUS_FILES = frozenset({"home-assistant/packages/ecco_pro.yaml"})
WORDING_FILES = frozenset({"registry/inverter_capabilities.yaml"})
TARGETS = tuple(sorted({
    SELF_REL,
    "docs/SYSTEM_HEALTH_ARCHITECTURE.md",                         # B.4 SANITISE (kept at its path; B.3)
    "frontend/ecco-energy-actions-card/README.md",
    "frontend/ecco-energy-actions-card/examples/ecco-example.yaml",
    "frontend/ecco-energy-actions-card/test/schedule.test.ts",
    "frontend/ecco-energy-flow-card/DESIGN.md",
    "frontend/ecco-energy-flow-card/examples/ecco-example.yaml",
    "home-assistant/dashboards/ecco_pro.yaml",
    "home-assistant/packages/ecco_canonical_telemetry.yaml",
    "home-assistant/packages/ecco_dump_to_grid_schedule.yaml",
    "home-assistant/packages/ecco_fallback_profile_actions.yaml",
    "home-assistant/packages/ecco_fallback_status.yaml",
    "home-assistant/packages/ecco_free_power_schedule.yaml",
    "home-assistant/packages/ecco_manual_controls_helpers.yaml",
    "home-assistant/packages/ecco_pro.yaml",
    "home-assistant/packages/ecco_runtime_config.yaml",
    "home-assistant/packages/ecco_supervision_heartbeat.yaml",
    "home-assistant/packages/ecco_system_health.yaml",
    "home-assistant/packages/ecco_tou_schedule.yaml",
    "home-assistant/prototypes/intelligence-v1/ecco_intelligence_v1_prototype_dashboard.yaml",   # Intelligence (spec H.4 item 5)
    "home-assistant/tests/test_ecco_dump_to_grid_schedule_package.py",
    "home-assistant/tests/test_ecco_fallback_packages.py",
    "home-assistant/tests/test_ecco_shadow_check_ux.py",
    "home-assistant/tests/test_ecco_system_health_package.py",
    "influxdb/diagnostics/ecco_battery_outlook_5m_shadow_preview.flux",
    "influxdb/diagnostics/ecco_battery_outlook_scorer_soc_preview.flux",
    "influxdb/diagnostics/ecco_canonical_5m_history_check.flux",
    "influxdb/diagnostics/ecco_canonical_coverage_check.flux",
    "influxdb/diagnostics/ecco_canonical_vs_raw_agreement.flux",
    "influxdb/diagnostics/history_depth_check.flux",
    "influxdb/diagnostics/latest_ecco_5m_point.flux",
    "influxdb/diagnostics/latest_ecco_raw_point.flux",
    "influxdb/diagnostics/test_telemetry_selection_logic.py",
    "influxdb/ecco_influxdb_options_v1_2.yaml",
    "influxdb/ecco_influxdb_options_v1_3.yaml",
    "influxdb/tasks/ecco_battery_outlook_5m.flux",
    "influxdb/tasks/ecco_battery_outlook_score_daily.flux",
    "intelligence/tests/test_intelligence_dashboard_prototype.py",                              # Intelligence (spec H.4 item 5)
    "intelligence/tools/preview_states.json",                                                  # Intelligence (spec H.4 item 5)
    "registry/health_reason_codes.yaml",
    "registry/inverter_capabilities.yaml",
    "registry/system_health_checks.yaml",
    "registry/tests/_fbb1_scope.py",
    "registry/tests/_fbb2_scope.py",
    "registry/tests/test_capability_registry.py",
    "registry/tests/test_failback_shadow_evaluator.py",
    "registry/tests/test_failback_shadow_ha_contract.py",
    "registry/tests/test_fallback_capture_scope.py",
    "registry/tests/test_fallback_ha_contract.py",
    "registry/tests/test_fallback_profile_schema.py",
    "registry/tests/test_fallback_recovery_dashboard.py",
    "registry/tests/test_fallback_save_scope.py",
    "registry/tests/test_fallback_save_static_pins.py",
    "registry/tests/test_free_power_recovery_evidence.py",
    "registry/tests/test_supervision_heartbeat_observe_only.py",
    "tools/ecco-flight-recorder.ps1",                             # B.2 SANITISE
    "tools/ecco-snapshot.ps1",                                    # B.2 SANITISE
}))

# The targets whose PRIVATE text a proof consumes (the chain reverter, or an older suite's PUB0: private_view edit). private_view() of
# any other target raises, so a new consumer has to be declared here (and in test_pub0_transition.py's ledger).
PROOF_VIEWS = frozenset({
    "registry/inverter_capabilities.yaml",                        # chain-pinned (_scope_chain.PUB0)
    "home-assistant/dashboards/ecco_pro.yaml",                    # FB-C3 / FB-B3 reverters and pins, Energy Actions block pin
    "home-assistant/packages/ecco_fallback_status.yaml",          # FB-B3 status-code / subline template pins
    "home-assistant/packages/ecco_supervision_heartbeat.yaml",    # FB-B3 heartbeat package pin
    "influxdb/ecco_influxdb_options_v1_2.yaml",                   # FB-B3 v1.2 pin
    "frontend/ecco-energy-actions-card/README.md",                # the Energy Actions frontend-folder pins (three suites)
    "frontend/ecco-energy-actions-card/examples/ecco-example.yaml",
    "frontend/ecco-energy-actions-card/test/schedule.test.ts",
})

# Token-bearing files pub0 deliberately does NOT sanitise, with the spec class that keeps them out of the public export (they are
# removed or rewritten by the later curation / docs jobs, never exported as they are). Informational: a token-bearing file in
# neither list is REPORTED by test_pub0_transition.py, not failed, so private development never goes red for carrying site data.
NOT_EXPORTED: dict = {}
# (The private-history files once listed here - CHANGELOG.md, CURRENT_STATE.md, the private design records, the superseded v7
# dashboards and their generators - are not part of the curated public-export tree at all; PUBLIC_RELEASE_BUILD_SPEC B.)


class Pub0Error(AssertionError):
    """A pub0 site, count or hash does not match its declaration (a failed proof, never a skipped one)."""


def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def line_sha(line: str) -> str:
    return sha(line)[:16]


def read_repo(rel: str, root: Path | None = None) -> str:
    """A repo text file as the suites read it (Path.read_text: universal newlines -> LF)."""
    return ((root or REPO) / rel).read_text(encoding="utf-8")


# ---------------------------------------------------------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------------------------------------------------------
def fingerprint(files: list) -> str:
    """Deterministic sha256 of the canonical JSON of the manifest's file records (pinned in _scope_chain.PUB0_FINGERPRINT)."""
    return sha(json.dumps(files, sort_keys=True, separators=(",", ":"), ensure_ascii=True))


@lru_cache(maxsize=None)
def _manifest_cached(path: str) -> dict:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def manifest() -> dict:
    return _manifest_cached(str(REPO / MANIFEST_REL))


def records(m: dict | None = None) -> dict:
    return {f["path"]: f for f in (m or manifest())["files"]}


def is_target(rel: str, m: dict | None = None) -> bool:
    return rel in records(m)


def _sites_by_line(rec: dict) -> list:
    return [(int(n), h, [(int(c), k) for c, k in sites]) for n, h, sites in rec["lines"]]


# ---------------------------------------------------------------------------------------------------------------------------
# The two directions
# ---------------------------------------------------------------------------------------------------------------------------
def _private_len(kind: str) -> int:
    return OCTOPUS_LEN[kind] if kind in OCTOPUS_LEN else len(PRIVATE_TOKEN[kind])


def _octopus_masked(rel: str, private_text: str, rec: dict) -> tuple[str, dict]:
    """The private text with every declared Octopus site replaced by its placeholder (the slug untouched) and the values found."""
    lines = private_text.split("\n")
    values: dict[str, set] = {}
    for n, _h, sites in _sites_by_line(rec):
        if n > len(lines):
            raise Pub0Error(f"pub0 {rel}: declared line {n} is past the end of the file ({len(lines)} lines)")
        line, out, pos, delta = lines[n - 1], [], 0, 0
        for col, kind in sites:
            pcol = col - delta
            plen = _private_len(kind)
            tok = line[pcol:pcol + plen]
            if kind in OCTOPUS_SHAPE:
                if not OCTOPUS_SHAPE[kind].fullmatch(tok):
                    raise Pub0Error(f"pub0 {rel}:{n}: no {kind}-shaped value at column {pcol}")
                values.setdefault(kind, set()).add(tok)
                out.append(line[pos:pcol] + OCTOPUS_PLACEHOLDER[kind])
                pos = pcol + plen
            delta += len(PUBLIC_TOKEN[kind]) - plen
        if any(k in OCTOPUS_SHAPE for _c, k in sites):
            lines[n - 1] = "".join(out) + line[pos:]
    return "\n".join(lines), values


def forward(rel: str, private_text: str, m: dict | None = None) -> str:
    """Private (source) text -> the public text. Accepts ONLY the declared source; raises Pub0Error otherwise."""
    recs = records(m)
    if rel not in recs:
        raise Pub0Error(f"pub0: {rel} is not a pub0 target")
    rec = recs[rel]
    masked, values = _octopus_masked(rel, private_text, rec)
    for kind, vals in values.items():
        if len(vals) != 1:
            raise Pub0Error(f"pub0 {rel}: {len(vals)} different {kind} values (exactly one is declared)")
    if "import_mpan" in values and values["import_mpan"] == values.get("export_mpan"):
        raise Pub0Error(f"pub0 {rel}: the import and export MPAN are the same value")
    if sha(masked) != rec["source_sha256"]:
        raise Pub0Error(f"pub0 {rel}: the source is not the declared pub0 source (sha256 {sha(masked)[:16]} != "
                        f"{rec['source_sha256'][:16]}); regenerate the manifest only for a deliberate new export base")
    lines = masked.split("\n")
    n_prefix_sites = n_octo_sites = n_wording_sites = n_attribution_sites = 0
    for n, h, sites in _sites_by_line(rec):
        line, out, pos, delta = lines[n - 1], [], 0, 0
        for col, kind in sites:
            pcol = col - delta
            if kind in OCTOPUS_SHAPE:            # already the placeholder (masked above)
                plen = len(OCTOPUS_PLACEHOLDER[kind])
                n_octo_sites += kind == "meter_serial"
            else:
                plen = len(PRIVATE_TOKEN[kind])
                if line[pcol:pcol + plen] != PRIVATE_TOKEN[kind]:
                    raise Pub0Error(f"pub0 {rel}:{n}: expected {kind} token at column {pcol}")
                n_prefix_sites += kind in ("slug", "keep", "keep_prefix")
                n_wording_sites += kind == "wording"
                n_attribution_sites += kind == "attribution"
            out.append(line[pos:pcol] + PUBLIC_TOKEN[kind])
            pos = pcol + plen
            delta += len(PUBLIC_TOKEN[kind]) - plen
        new = "".join(out) + line[pos:]
        if line_sha(new) != h:
            raise Pub0Error(f"pub0 {rel}:{n}: the public line does not hash to the recorded {h}")
        lines[n - 1] = new
    public = "\n".join(lines)
    # Coverage: every occurrence is a declared site - no more, no fewer.
    if private_text.count(PRIVATE_AREA_PREFIX) != n_prefix_sites:
        raise Pub0Error(f"pub0 {rel}: {private_text.count(PRIVATE_AREA_PREFIX)} private-prefix occurrences, {n_prefix_sites} declared")
    if rel != SELF_REL and private_text.count(WORDING_PRIVATE) != n_wording_sites:
        raise Pub0Error(f"pub0 {rel}: {private_text.count(WORDING_PRIVATE)} provenance-wording occurrences, {n_wording_sites} declared")
    if rel != SELF_REL and private_text.count(ATTRIBUTION_PRIVATE) != n_attribution_sites:
        raise Pub0Error(f"pub0 {rel}: {private_text.count(ATTRIBUTION_PRIVATE)} personal-attribution occurrences, "
                        f"{n_attribution_sites} declared")
    if len(OCTOPUS_ID.findall(private_text)) != n_octo_sites:
        raise Pub0Error(f"pub0 {rel}: {len(OCTOPUS_ID.findall(private_text))} Octopus ids, {n_octo_sites} declared")
    for kind, vals in values.items():
        for v in vals:
            if v in public:
                raise Pub0Error(f"pub0 {rel}: a {kind} value survives outside the declared sites")
    if sha(public) != rec["result_sha256"]:
        raise Pub0Error(f"pub0 {rel}: the public text does not hash to the recorded result {rec['result_sha256'][:16]}")
    return public


def reverse(rel: str, public_text: str, m: dict | None = None) -> str:
    """Public text -> the exact private representation (proof direction; edit-local, like every chain reverter). Octopus sites keep
    their placeholders (irreversible by design)."""
    recs = records(m)
    if rel not in recs:
        raise Pub0Error(f"pub0: {rel} is not a pub0 target")
    lines = public_text.split("\n")
    for n, h, sites in _sites_by_line(recs[rel]):
        if n > len(lines) or line_sha(lines[n - 1]) != h:
            raise Pub0Error(f"pub0 {rel}:{n}: not the recorded pub0 public line (its edit is absent or altered)")
        line, out, pos = lines[n - 1], [], 0
        for col, kind in sites:
            tok = PUBLIC_TOKEN[kind]
            if line[col:col + len(tok)] != tok:
                raise Pub0Error(f"pub0 {rel}:{n}: expected the public {kind} token at column {col}")
            out.append(line[pos:col] + (PRIVATE_TOKEN[kind] if kind in REVERSIBLE else tok))
            pos = col + len(tok)
        lines[n - 1] = "".join(out) + line[pos:]
    return "\n".join(lines)


def reverter(rel: str):
    """The chain reverter of a pub0-edited chain-pinned artifact (_scope_chain.PUB0)."""
    def revert(text: str) -> str:
        return reverse(rel, text)
    revert.__name__ = f"pre_pub0_{Path(rel).stem}"
    return revert


def private_view(rel: str, text: str) -> str:
    """What an older suite hashes / reverts: `text` exactly as the private tree spells it. The identity in the private tree and for
    every file pub0 does not touch; reverse() in the public export (a declared site that is absent or altered raises). A target that
    is not a declared PROOF_VIEW raises in both trees."""
    if not is_target(rel):
        return text
    if rel not in PROOF_VIEWS:
        raise Pub0Error(f"pub0: {rel} is not a declared PROOF_VIEW (declare it in _pub0_scope.PROOF_VIEWS and the PUB0 ledger)")
    return reverse(rel, text) if EXPORTED else text


def private_view_edited(rel: str, text: str, line_edits: dict) -> str:
    """private_view(rel, text) with a suite's own exact LINE edit applied at the same line numbers: every line of `text` equal to a key
    of `line_edits` becomes the mapped value (None removes it). pub0 maps a file line for line, so this is the private text of the
    suite's derived (reverted) text - for an older suite that pins a template it derives by replacing whole lines."""
    out = []
    for t, p in zip(text.split("\n"), private_view(rel, text).split("\n")):
        if t in line_edits:
            if line_edits[t] is not None:
                out.append(line_edits[t])
        else:
            out.append(p)
    return "\n".join(out)


def private_view_bytes(rel: str, data: bytes) -> bytes:
    """private_view() for a suite that hashes LF-normalised bytes (the frontend-folder pins)."""
    if not is_target(rel):
        return data
    return private_view(rel, data.decode("utf-8")).encode("utf-8")


# ---------------------------------------------------------------------------------------------------------------------------
# Generation (private tree only): the manifest is DERIVED from the private source, deterministic, round-trip verified
# ---------------------------------------------------------------------------------------------------------------------------
def _find_sites(rel: str, text: str) -> list:
    """[(line, private column, kind)] of every pub0 site in the private text, by the policy of the file."""
    out = []
    lines = text.split("\n")
    for i, line in enumerate(lines, 1):
        found = []
        if rel in OCTOPUS_FILES:
            for mo in OCTOPUS_ID.finditer(line):
                found.append((mo.start(1), "meter_serial"))
                found.append((mo.start(2), "export_mpan" if mo.group(3) else "import_mpan"))
        start = 0
        while True:
            j = line.find(PRIVATE_AREA_PREFIX, start)
            if j < 0:
                break
            if line.startswith(PRIVATE_SLUG, j):
                found.append((j, "keep" if rel in KEEP_FILES else "slug"))
            elif rel == SELF_REL and line.startswith(f'PRIVATE_AREA_PREFIX = "{PRIVATE_AREA_PREFIX}"', j - len('PRIVATE_AREA_PREFIX = "')):
                found.append((j, "keep_prefix"))
            else:
                raise Pub0Error(f"pub0 generate {rel}:{i}: a bare private prefix that is neither the slug nor the declared literal")
            start = j + len(PRIVATE_AREA_PREFIX)
        if rel in WORDING_FILES:
            start = 0
            while (j := line.find(WORDING_PRIVATE, start)) >= 0:
                found.append((j, "wording"))
                start = j + len(WORDING_PRIVATE)
        if rel in ATTRIBUTION_FILES:
            start = 0
            while (j := line.find(ATTRIBUTION_PRIVATE, start)) >= 0:
                found.append((j, "attribution"))
                start = j + len(ATTRIBUTION_PRIVATE)
        if rel == SELF_REL and EXPORT_FLAG_LINE.fullmatch(line):
            if line != "EXPORTED = False":
                raise Pub0Error("pub0 generate: the private tree must carry EXPORTED = False")
            found.append((len("EXPORTED = "), "export_flag"))
        out.extend((i, c, k) for c, k in sorted(found))
    return out


def generate(root: Path | None = None) -> dict:
    """The manifest for the private tree at `root` (default: this repo). Raises if the tree is already an export."""
    files = []
    for rel in TARGETS:
        text = read_repo(rel, root)
        sites = _find_sites(rel, text)
        if not sites:
            raise Pub0Error(f"pub0 generate: target {rel} carries no pub0 token")
        lines = text.split("\n")
        by_line: dict[int, list] = {}
        for n, c, k in sites:
            by_line.setdefault(n, []).append((c, k))
        recs_lines = []
        for n in sorted(by_line):
            line, out, pos, pub_sites, delta = lines[n - 1], [], 0, [], 0
            for c, k in by_line[n]:
                plen = _private_len(k)
                out.append(line[pos:c] + PUBLIC_TOKEN[k])
                pub_sites.append([c + delta, k])
                delta += len(PUBLIC_TOKEN[k]) - plen
                pos = c + plen
            new = "".join(out) + line[pos:]
            recs_lines.append([n, line_sha(new), pub_sites])
            lines[n - 1] = new
        public = "\n".join(lines)
        rec = {"path": rel, "result_sha256": sha(public), "lines": recs_lines}
        rec["source_sha256"] = sha(reverse(rel, public, {"files": [rec]}))
        files.append({"path": rel, "source_sha256": rec["source_sha256"], "result_sha256": rec["result_sha256"], "lines": recs_lines})
        m1 = {"files": [files[-1]]}
        if forward(rel, text, m1) != public or (rel not in OCTOPUS_FILES and reverse(rel, public, m1) != text):
            raise Pub0Error(f"pub0 generate {rel}: round trip failed")
    return {"schema": SCHEMA, "transition": "pub0",
            "kinds": {k: {"public": PUBLIC_TOKEN[k] if k not in ("keep", "keep_prefix") else "(kept)",
                          "reversible": k in REVERSIBLE} for k in KINDS},
            "fingerprint": fingerprint(files), "files": files}


def dumps(m: dict) -> str:
    """The canonical manifest text (one file record per line, so a review diff shows exactly which file moved)."""
    head = {k: v for k, v in m.items() if k != "files"}
    body = ",\n".join("  " + json.dumps(f, sort_keys=True, separators=(",", ":")) for f in m["files"])
    return json.dumps(head, sort_keys=True, indent=1)[:-2] + ',\n "files": [\n' + body + "\n ]\n}\n"
