#!/usr/bin/env python3
"""Render an engine report into the Home Assistant entity contract (PROTOTYPE, never deployed).

Writes a template-sensor package whose sensors carry a frozen report as static state/attributes, so the
prototype dashboard (home-assistant/prototypes/intelligence-v1/) shows real engine output without any engine
running in Home Assistant. The SAME mapping (report -> five sensors) is what a future publisher would produce
live, which is why it lives here and is unit-tested.

    python intelligence/tools/render_ha_prototype.py REPORT.json ACCURACY.json OUT.yaml

Entity contract (all read-only, all marked mode=SHADOW):
  sensor.ecco_intelligence_status       state = status (LEARNING_NORMALLY, ...); report metadata, reasons, anomalies
  sensor.ecco_intelligence_predicted    state = predicted whole-day kWh (p50); forecasts with bands; PV day forecasts
  sensor.ecco_intelligence_recommended  state = recommended overnight target SOC %; target, export, session
  sensor.ecco_intelligence_trajectory   state = number of points; points = [[iso, median, low, high], ...]
  sensor.ecco_intelligence_accuracy     state = 7-day day-load MAE (kWh); per-kind accuracy, last-14 series, insights
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

HEADER = """# PROTOTYPE ONLY - NOT DEPLOYED - NOT IN deployment/ha-manifest.yaml.
# Generated by intelligence/tools/render_ha_prototype.py from an engine report on a SYNTHETIC household ({src}).
# Template sensors with FROZEN values so the prototype dashboard can render engine output before any engine runs
# in Home Assistant. They are read-only display sensors: nothing here calls a service or writes anything.
# Do not copy to /config/packages without an owner decision (see docs/intelligence/ECCO_INTELLIGENCE_V1_ARCHITECTURE.md).
"""


def r(x, n=2):
    return None if x is None else round(float(x), n)


def band(f: dict | None) -> list | None:
    """[p10, p50, p90, label, n_residuals, empirical_coverage, notes, window_start, window_end]; None when the engine
    marked the forecast unusable (INSUFFICIENT), so a card can never show its numbers."""
    if not f or f.get("usable") is False:
        return None
    return [r(f["p10"]), r(f["p50"]), r(f["p90"]), f.get("label"), f.get("n_residuals"), f.get("empirical_coverage"),
            f.get("notes", []), f.get("t0"), f.get("t1")]


def contract(report: dict, accuracy: dict) -> dict[str, tuple[str, dict]]:
    pred = report["predicted"]
    rec = report["recommended"]
    ot = rec.get("overnight_target") or {}
    sx = rec.get("safe_export") or {}
    rp = rec.get("predicted") or {}
    status_attrs = {
        "mode": report["mode"], "applies_nothing": report["applies_nothing"], "generated_for": report["generated_for"],
        "model_version": report["model_version"], "config_hash": report["config_hash"],
        "confidence": report["confidence"], "notes": report["notes"],
        "reasons": [x["text"] for x in rec.get("reasons", [])], "reason_codes": [x["code"] for x in rec.get("reasons", [])],
        "uncertainty": rec.get("uncertainty", []),
        "anomaly_flags": {k: report["anomalies"].get(k) for k in ("abnormal_load_now", "excess_kw_now", "base_load_kw", "base_load_norm_kw")},
        "assumptions": rec.get("assumptions", []), "anomalies": report["anomalies"]["anomalies"],
        "floor_pct": rec.get("floor_pct"), "desired_min_pct": rec.get("desired_min_pct"), "reserve": rec.get("reserve"),
        "weekday_effect": report.get("weekday_effect"),
        # true only in the frozen prototype package: tells the dashboard to time-shift the sample so it sits at "now"
        "frozen_sample": True,
    }
    forecasts = {k: band(v) for k, v in pred.items() if isinstance(v, dict) and "p10" in v}
    pv = {}
    for k, v in report.get("pv", {}).items():
        if k == "today_reanchor" or not isinstance(v, dict):
            continue
        pv[k] = {"source": v["source"], "raw": r(v["raw_kwh"], 1), "ratio": r(v["ratio"], 3), "p10": r(v["p10"], 1),
                 "p50": r(v["p50"], 1), "p90": r(v["p90"], 1), "label": v["label"], "notes": v["notes"]}
    predicted_attrs = {
        "mode": "SHADOW", "forecasts": forecasts, "pv_days": pv, "day_so_far_kwh": pred.get("day_so_far_kwh"),
        "day_projection_kwh": pred.get("day_projection_kwh"), "sunrise": pred.get("sunrise"), "sunset": pred.get("sunset"),
        "next_sunrise": pred.get("next_sunrise"), "pv_reanchor_today": (report.get("pv") or {}).get("today_reanchor"),
        "useful_pv_start": pred.get("useful_pv_start"),
    }
    recommended_attrs = {
        "mode": "SHADOW", "target": ot, "predicted_soc": {k: r(v, 1) if isinstance(v, float) else v for k, v in rp.items()},
        "safe_export": sx, "saving_session": rec.get("saving_session"), "status": rec.get("status"),
    }
    traj = [[t["t"], t["soc_median"], t["soc_low"], t["soc_high"]] for t in rec.get("trajectory", [])]
    acc_attrs = {
        "mode": "SHADOW", "last_7_days": accuracy.get("accuracy_last_7_days", {}),
        # compact rows {t: 'MM-DD', p: predicted, lo, hi: p10/p90 band, a: actual, ok: inside band} to stay well under 16 kB
        "series_last_14": {k: [{"t": x["target_end_local"][5:10], "p": x["predicted"], "lo": x["band_low"], "hi": x["band_high"],
                                "a": x["actual"], "ok": x["in_band"]} for x in v]
                           for k, v in accuracy.get("series_last_14", {}).items()
                           if k in ("load_kwh:day", "load_kwh:cheap_window", "load_kwh:morning", "pv_kwh:day")},
        "error_sign": "error = actual - predicted; positive bias = under-forecast",
        "insights": accuracy.get("insights", []),
    }
    mae = (accuracy.get("accuracy_last_7_days", {}).get("load_kwh:day") or {}).get("mae")
    return {
        "status": (report["status"], status_attrs),
        "predicted": (str(r(pred["day"]["p50"], 1)), predicted_attrs),
        "recommended": (str(ot.get("recommended_target_soc_pct", "unknown")), recommended_attrs),
        "trajectory": (str(len(traj)), {"mode": "SHADOW", "points": traj}),
        "accuracy": (str(r(mae, 2)) if mae is not None else "unknown", acc_attrs),
    }


def render(report: dict, accuracy: dict, src: str) -> str:
    out = [HEADER.format(src=src), "template:", "  - sensor:"]
    names = {"status": "ECCO Intelligence Status", "predicted": "ECCO Intelligence Predicted",
             "recommended": "ECCO Intelligence Recommended", "trajectory": "ECCO Intelligence Trajectory",
             "accuracy": "ECCO Intelligence Accuracy"}
    units = {"predicted": "kWh", "recommended": "%", "accuracy": "kWh"}
    icons = {"status": "mdi:brain", "predicted": "mdi:chart-line", "recommended": "mdi:lightbulb-on-outline",
             "trajectory": "mdi:battery-clock", "accuracy": "mdi:target"}
    for key, (state, attrs) in contract(report, accuracy).items():
        out.append(f"      - name: {names[key]}")
        out.append(f"        unique_id: ecco_intelligence_{key}")
        out.append(f"        icon: {icons[key]}")
        if key in units:
            out.append(f"        unit_of_measurement: \"{units[key]}\"")
        out.append(f"        state: {json.dumps(state)}")
        out.append("        attributes:")
        for k, v in attrs.items():
            out.append(f"          {k}: {json.dumps(v, separators=(',', ':'), default=str)}")
    return "\n".join(out) + "\n"


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__)
        return 2
    rep = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    acc = json.loads(Path(sys.argv[2]).read_text(encoding="utf-8"))
    Path(sys.argv[3]).write_text(render(rep, acc, Path(sys.argv[1]).name), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
